### Get all Products
GET http://localhost:5000/api/products


### Get single Products
GET http://localhost:5000/api/products/1

### Create a new Product
POST http://localhost:5000/api/products
Content-Type: application/json

{"title":"product one","price":12}



### Update a Product
PUT  http://localhost:5000/api/products/1
Content-Type: application/json

{"title":"product one"}

### delete a Product
DELETE   http://localhost:5000/api/products/1
